### ISSUE TITLE
With React 0.13

### ISSUE THREAD

**Issue by uiur** [gajus/react-outside-event#1]
I'm using React 0.13, but it seems that `react-dom` is not available for React 0.13.

So I just replaced `import ReactDOM from 'react-dom';` with`import ReactDOM from 'react';` and it works well.

I think this workaround is not good. 

Do you have a plan to support React 0.13? Or any ideas about a better workaround?

**Comment by gajus** [comment]
You did it right. In fact, in React 0.14.0-beta3 `react-dom` is just a link to the main `react` package. This will change in future, though.

There is nothing in the roadmap to support 0.13, but facebook.com is already using 0.14.0-beta3. 0.14 should be released some time soon too.

**Comment by uiur** [comment]
I will wait for 0.14. Thanks :)
