### ISSUE TITLE
Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by amihaiemil** [gajus/react-outside-event#4]
This error occurs when I click "outside" of the component which is not rendered yet.
So the onOutsideEvent is triggered even if the component is not visible.

See the search widget from this page: http://www.amihaiemil.com
The component which should disappear on outside click is the list of results. Type "test".
The error appears on the page at every click.

**Comment by gajus** [comment]
A PR is welcome.

**Comment by amihaiemil** [comment]
Right; I'll try to look into it :D

**Comment by amihaiemil** [comment]
@gajus I also deployed and it's working fine, thanks. Closing this :)
