### ISSUE TITLE
Automate devops with rultor

### ISSUE THREAD

**Issue by amihaiemil** [gajus/react-outside-event#6]
You could use [rultor](http://www.rultor.com) to automate the devops.
You could say ``@rultor release, tag is x.x.x``, and the project would be released on npm :)

**Comment by gajus** [comment]
1. It is not clear what is Rultor or what it does. The documentation is lacking.
2. I am using semantic-release for any projects that often get released. Assuming thats the intended use for Rultor.

**Comment by amihaiemil** [comment]
Documentation is linked to the main homepage, which I gave in the description :) you can do anything with it, basically.

Here's how I use it to deploy a js file to production:
  http://www.amihaiemil.com/2017/02/13/github-automatically-deploy-files-from-one-repo-to-another.html
